### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by bit-prophet** [myaghobi/PHP-Board#1]
Hi, I checked your script, it's useful.
I suggest you to add these options too:

1. Check write permission!
2. Change timezone.

**Comment by myaaghubi** [comment]
@mohsennouri thank you for your suggestion. Please check out 940454cf8c4cbd277f932c82580f12297431db7b.
Please let me know if you have any further suggestions or corrections.

**Comment by bit-prophet** [comment]
Good job.
Another ideas:

1- Don't use exact words like "session.gc_maxlifetime" I think "Session lifetime" is better or:
max_file_uploads => max file uploads
mysqli.default_port => MySQL port
zlib.output_compression => Output compression
etc

This is more understandable for people, and show the real name like "max_file_uploads"in title. 
Also I think some items needs a few description, for example "safe_mode" somebody doesn't know what is it for, of course they can google D:


2- In the file manager it's allowed to remove itself! I think it not safe and it's better to hide and disallow any change on "phpboard" directory or "index.php" that located in root.

3- If you use a higher resolution icon for directory, it would be great.

I liked your script it's handy

**Comment by myaaghubi** [comment]
@mohsennouri, please check out the [Pre-release](https://github.com/myaghobi/PHP-Board/releases/tag/v0.4.7) I have released.
I'm not sure about not showing the exact phrase as exists in php.ini, but making some descriptions is a good idea.
Also, feel free to make any changes and ask for PR.
